// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using POC.LaunchDarkly.Data;

#nullable disable

namespace POC.LaunchDarkly.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("POC.LaunchDarkly.Domain.Entities.Emprestimo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Identificador do empréstimo");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR(11)")
                        .HasComment("CPF do solicitante do empréstimo");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamptz")
                        .HasComment("Data de criação do empréstimo");

                    b.Property<string>("Finalidade")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR(100)")
                        .HasComment("Finalidade declarada para o empréstimo");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasComment("Número da conta vinculada ao empréstimo");

                    b.Property<int>("PrazoEmMeses")
                        .HasColumnType("INT")
                        .HasComment("Prazo de pagamento em meses");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasComment("Status atual do empréstimo");

                    b.Property<decimal>("ValorSolicitado")
                        .HasColumnType("DECIMAL(18,2)")
                        .HasComment("Valor solicitado para o empréstimo");

                    b.HasKey("Id");

                    b.ToTable("Emprestimo");
                });
#pragma warning restore 612, 618
        }
    }
}
